module.exports = {
  content: ["./app/templates/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "outline-variant": "#bdc9c6",
        "surface-container-low": "#f1f4f3",
        "on-secondary-fixed-variant": "#2e4c48",
        "surface-container": "#ebefed",
        "tertiary-fixed-dim": "#ffb598",
        "primary-fixed-dim": "#80d5cb",
        "primary-container": "#0f766e",
        "tertiary-container": "#9c573a",
        "outline": "#6e7977",
        "on-primary-fixed": "#00201d",
        "surface-variant": "#e0e3e1",
        "inverse-on-surface": "#eef1f0",
        "surface-container-high": "#e5e9e7",
        "primary": "#005c55",
        "on-tertiary-fixed": "#370e00",
        "secondary-fixed": "#c8e9e4",
        "error": "#ba1a1a",
        "inverse-surface": "#2d3130",
        "on-primary-fixed-variant": "#00504a",
        "on-tertiary-fixed-variant": "#72361b",
        "on-background": "#181c1c",
        "on-tertiary-container": "#ffe5db",
        "secondary": "#466460",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#80d5cb",
        "tertiary": "#7f4025",
        "primary-fixed": "#9cf2e8",
        "surface-dim": "#d7dbd9",
        "secondary-fixed-dim": "#accdc8",
        "on-surface-variant": "#3e4947",
        "error-container": "#ffdad6",
        "on-primary-container": "#a3faef",
        "on-secondary-fixed": "#00201d",
        "surface-bright": "#f7faf8",
        "tertiary-fixed": "#ffdbce",
        "on-secondary": "#ffffff",
        "surface-tint": "#006a63",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "background": "#f5f7fa",
        "secondary-container": "#c5e6e1",
        "surface-container-highest": "#e0e3e1",
        "on-secondary-container": "#4a6864",
        "surface": "#ffffff",
        "on-surface": "#181c1c",
        "status-success": "#10b981",
        "status-error": "#ef4444",
        "chart-1": "#005c55",
        "chart-2": "#4f46e5",
        "chart-3": "#f59e0b",
        "chart-4": "#3b82f6",
        "chart-5": "#64748b"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        margin_desktop: "32px",
        sidebar_width: "240px",
        stack_lg: "24px",
        stack_md: "16px",
        stack_sm: "8px",
        container_max_width: "1280px",
        margin_mobile: "16px",
        gutter: "24px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "h1-mobile": ["Manrope"],
        "label-caps": ["Inter"],
        "h2": ["Manrope"],
        "h1": ["Manrope"],
        "body-md": ["Inter"],
        "h3": ["Manrope"],
        "body-lg": ["Inter"],
        "number-display": ["Inter"]
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "h1-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "h2": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h1": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "h3": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "number-display": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      },
      boxShadow: {
        card: "0 1px 3px rgba(16,24,40,0.06)",
        "card-hover": "0 4px 6px rgba(16,24,40,0.1)"
      }
    }
  },
};
