module.exports = {
  content: ["./app/templates/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "outline-variant": "#d8deea",
        "surface-container-low": "#f0f5fa",
        "on-secondary-fixed-variant": "#5f4a22",
        "surface-container": "#edf2f7",
        "tertiary-fixed-dim": "#e2c991",
        "primary-fixed-dim": "#c98f8d",
        "primary-container": "#7f0705",
        "tertiary-container": "#f4ead5",
        "outline": "#6b7280",
        "on-primary-fixed": "#1f2a40",
        "surface-variant": "#e7ecf5",
        "inverse-on-surface": "#f7f9fc",
        "surface-container-high": "#e7ecf5",
        "primary": "#9e0906",
        "on-tertiary-fixed": "#3f3216",
        "secondary-fixed": "#f4ead5",
        "error": "#9e0906",
        "inverse-surface": "#1f2a40",
        "on-primary-fixed-variant": "#7f0705",
        "on-tertiary-fixed-variant": "#6f5524",
        "on-background": "#111827",
        "on-tertiary-container": "#3f3216",
        "secondary": "#1f2a40",
        "on-error": "#ffffff",
        "on-error-container": "#7f0705",
        "inverse-primary": "#e2c991",
        "tertiary": "#c9a96e",
        "primary-fixed": "#f3d8d7",
        "surface-dim": "#e4eaf4",
        "secondary-fixed-dim": "#e2d2ac",
        "on-surface-variant": "#4b5568",
        "error-container": "#f4d0cf",
        "on-primary-container": "#ffe7e6",
        "on-secondary-fixed": "#1f2a40",
        "surface-bright": "#f7f9fc",
        "tertiary-fixed": "#f6ecd7",
        "on-secondary": "#ffffff",
        "surface-tint": "#9e0906",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "background": "#f7f9fc",
        "secondary-container": "#c9a96e1f",
        "surface-container-highest": "#e4eaf4",
        "on-secondary-container": "#5f4a22",
        "surface": "#ffffff",
        "on-surface": "#111827",
        "status-success": "#22c55e",
        "status-error": "#9e0906",
        "chart-1": "#9e0906",
        "chart-2": "#1f2a40",
        "chart-3": "#c9a96e",
        "chart-4": "#3b82f6",
        "chart-5": "#6b7280"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        margin_desktop: "32px",
        sidebar_width: "240px",
        stack_lg: "24px",
        stack_md: "16px",
        stack_sm: "8px",
        container_max_width: "1280px",
        margin_mobile: "16px",
        gutter: "24px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "h1-mobile": ["Manrope"],
        "label-caps": ["Inter"],
        "h2": ["Manrope"],
        "h1": ["Manrope"],
        "body-md": ["Inter"],
        "h3": ["Manrope"],
        "body-lg": ["Inter"],
        "number-display": ["Inter"]
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "h1-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "h2": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h1": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "h3": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "number-display": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      },
      boxShadow: {
        card: "0 1px 3px rgba(31,42,64,0.08)",
        "card-hover": "0 8px 20px rgba(31,42,64,0.12)"
      }
    }
  },
};
